### ISSUE TITLE
File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2)

### ISSUE THREAD

**Issue by nygage** [brycelarge/xteve-vpn#15]
Hello Bryce, 

Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. 

> -----END CERTIFICATE-----
> </ca>2023-03-19 17:32:30 [OpenVPN] Adding  to /etc/resolv.conf
> 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
> 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2)
> Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2)
> Options error: Please correct these errors.

I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container

>      "Env": [
>                 "DEBUG=true",
>                 "PGID=1001",
>                 "OPENVPN_PROVIDER=CUSTOM",
>                 "LOCAL_NETWORK=192.168.0.0/24",
>                 "PRIVOXY_ENABLED=true",
>                 "NAME_SERVERS=1.1.1.1,1.0.0.1",
>                 "PUID=1001",
>                 "OPENVPN_USERNAME=******",
>                 "OPENVPN_PASSWORD=******",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                 "HOME=/root",
>                 "LANGUAGE=en_US.UTF-8",
>                 "LANG=en_US.UTF-8",
>                 "TERM=xterm",
>                 "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
>                 "S6_VERBOSITY=1",
>                 "S6_STAGE2_HOOK=/docker-mods",
>                 "XTEVE_BRANCH=master",
>                 "XTEVE_PORT=34400",
>                 "XTEVE_DEBUG=0",
>                 "TZ=Africa/Johannesburg",
>                 "OPENVPN_CONFIG=**None**",
>                 "CREATE_TUN_DEVICE=true",
>                 "OPENVPN_OPTIONS=",
>                 "OPENVPN_PROTOCOL=udp"
>             ],
> 

Could you please help me to figure out what can be happening? 

Thanks!

**Comment by brycelarge** [comment]
Hello,

 

I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out?

 

 

Kind Regards

Bryce

 

 

From: nygage ***@***.***>
Reply to: brycelarge/xteve-vpn ***@***.***>
Date: Sunday, 19 March 2023 at 17:42
To: brycelarge/xteve-vpn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15)

 

Hello Bryce,

Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files.

-----END CERTIFICATE-----
2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf
2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2)
Options error: Please correct these errors.

I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container
 "Env": [
            "DEBUG=true",
            "PGID=1001",
            "OPENVPN_PROVIDER=CUSTOM",
            "LOCAL_NETWORK=192.168.0.0/24",
            "PRIVOXY_ENABLED=true",
            "NAME_SERVERS=1.1.1.1,1.0.0.1",
            "PUID=1001",
            "OPENVPN_USERNAME=******",
            "OPENVPN_PASSWORD=******",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/root",
            "LANGUAGE=en_US.UTF-8",
            "LANG=en_US.UTF-8",
            "TERM=xterm",
            "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
            "S6_VERBOSITY=1",
            "S6_STAGE2_HOOK=/docker-mods",
            "XTEVE_BRANCH=master",
            "XTEVE_PORT=34400",
            "XTEVE_DEBUG=0",
            "TZ=Africa/Johannesburg",
            "OPENVPN_CONFIG=**None**",
            "CREATE_TUN_DEVICE=true",
            "OPENVPN_OPTIONS=",
            "OPENVPN_PROTOCOL=udp"
        ],
Could you please help me to figure out what can be happening?

Thanks!

**Comment by nygage** [comment]
> Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage ***@***.***> Reply to: brycelarge/xteve-vpn ***@***.***> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn ***@***.***> Cc: Subscribed ***@***.***> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files.
> […](#)
> -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [             "DEBUG=true",             "PGID=1001",             "OPENVPN_PROVIDER=CUSTOM",             "LOCAL_NETWORK=192.168.0.0/24",             "PRIVOXY_ENABLED=true",             "NAME_SERVERS=1.1.1.1,1.0.0.1",             "PUID=1001",             "OPENVPN_USERNAME=******",             "OPENVPN_PASSWORD=******",             "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",             "HOME=/root",             "LANGUAGE=en_US.UTF-8",             "LANG=en_US.UTF-8",             "TERM=xterm",             "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",             "S6_VERBOSITY=1",             "S6_STAGE2_HOOK=/docker-mods",             "XTEVE_BRANCH=master",             "XTEVE_PORT=34400",             "XTEVE_DEBUG=0",             "TZ=Africa/Johannesburg",             "OPENVPN_CONFIG=**None**",             "CREATE_TUN_DEVICE=true",             "OPENVPN_OPTIONS=",             "OPENVPN_PROTOCOL=udp"         ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


Hello,
Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer?

**Comment by brycelarge** [comment]
Yes there is a new build which I pushed just before replying to you.

 

 

Kind Regards

Bryce

 

 

From: nygage ***@***.***>
Reply to: brycelarge/xteve-vpn ***@***.***>
Date: Sunday, 19 March 2023 at 20:21
To: brycelarge/xteve-vpn ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15)

 

Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files.
…
-----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [             "DEBUG=true",             "PGID=1001",             "OPENVPN_PROVIDER=CUSTOM",             "LOCAL_NETWORK=192.168.0.0/24",             "PRIVOXY_ENABLED=true",             "NAME_SERVERS=1.1.1.1,1.0.0.1",             "PUID=1001",             "OPENVPN_USERNAME=",             "OPENVPN_PASSWORD=",             "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",             "HOME=/root",             "LANGUAGE=en_US.UTF-8",             "LANG=en_US.UTF-8",             "TERM=xterm",             "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",             "S6_VERBOSITY=1",             "S6_STAGE2_HOOK=/docker-mods",             "XTEVE_BRANCH=master",             "XTEVE_PORT=34400",             "XTEVE_DEBUG=0",             "TZ=Africa/Johannesburg",             "OPENVPN_CONFIG=None",             "CREATE_TUN_DEVICE=true",             "OPENVPN_OPTIONS=",             "OPENVPN_PROTOCOL=udp"         ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.***>

Hello,
Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer?

**Comment by nygage** [comment]
I'm not able to see It, the last commits i see are from 2 days ago. 
I've checked also to see if there is a dev branch, but i dont see It



> Yes there is a new build which I pushed just before replying to you. Kind Regards Bryce From: nygage ***@***.***> Reply to: brycelarge/xteve-vpn ***@***.***> Date: Sunday, 19 March 2023 at 20:21 To: brycelarge/xteve-vpn ***@***.***> Cc: ***@***.***" ***@***.***>, Comment ***@***.***> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. … -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [ "DEBUG=true", "PGID=1001", "OPENVPN_PROVIDER=CUSTOM", "LOCAL_NETWORK=192.168.0.0/24", "PRIVOXY_ENABLED=true", "NAME_SERVERS=1.1.1.1,1.0.0.1", "PUID=1001", "OPENVPN_USERNAME=", "OPENVPN_PASSWORD=", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "HOME=/root", "LANGUAGE=en_US.UTF-8", "LANG=en_US.UTF-8", "TERM=xterm", "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0", "S6_VERBOSITY=1", "S6_STAGE2_HOOK=/docker-mods", "XTEVE_BRANCH=master", "XTEVE_PORT=34400", "XTEVE_DEBUG=0", "TZ=Africa/Johannesburg", "OPENVPN_CONFIG=None", "CREATE_TUN_DEVICE=true", "OPENVPN_OPTIONS=", "OPENVPN_PROTOCOL=udp" ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.***> Hello, Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by brycelarge** [comment]
Are you looking at the git repo? I built and pushed up to docker hub so pulling the latest image has the fix.

 

I have not yet commit the fix, was waiting for confirmation it was working first.

 

 

Kind Regards

Bryce

 

 

From: nygage ***@***.***>
Reply to: brycelarge/xteve-vpn ***@***.***>
Date: Sunday, 19 March 2023 at 21:07
To: brycelarge/xteve-vpn ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15)

 

I'm not able to see It, the last commits i see are from 2 days ago.
I've checked also to see if there is a dev branch, but i dont see It

Yes there is a new build which I pushed just before replying to you. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 20:21 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. … -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [ "DEBUG=true", "PGID=1001", "OPENVPN_PROVIDER=CUSTOM", "LOCAL_NETWORK=192.168.0.0/24", "PRIVOXY_ENABLED=true", "NAME_SERVERS=1.1.1.1,1.0.0.1", "PUID=1001", "OPENVPN_USERNAME=", "OPENVPN_PASSWORD=", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "HOME=/root", "LANGUAGE=en_US.UTF-8", "LANG=en_US.UTF-8", "TERM=xterm", "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0", "S6_VERBOSITY=1", "S6_STAGE2_HOOK=/docker-mods", "XTEVE_BRANCH=master", "XTEVE_PORT=34400", "XTEVE_DEBUG=0", "TZ=Africa/Johannesburg", "OPENVPN_CONFIG=None", "CREATE_TUN_DEVICE=true", "OPENVPN_OPTIONS=", "OPENVPN_PROTOCOL=udp" ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Hello, Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

**Comment by nygage** [comment]
Oh, thanks for the clarification, i was manually building the image. I have tested with the new one image but it seems that it is not adding the information properly to the .ovpn file:

Original .ovpn file:

> # Crypto
> cipher AES-128-CBC
> auth SHA256
> auth-user-pass

After the script:

> # Crypto
> data-data-data-data-data-data-data-data-data-data-data-data-data-ciphersssssssssssss AES-128-CBC
> auth SHA256
> auth-user-pass /config/openvpn/custom-openvpn-credentials.txt

And the error which i'm receiving is the following one:

> 2023-03-19 22:11:01 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
> Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/configuration.ovpn:15: data-data-data-data-data-data-data-data-data-data-data-data-cipherssssssssssss (2.5.5)
> Use --help for more information.

Thanks! 

> Are you looking at the git repo? I built and pushed up to docker hub so pulling the latest image has the fix. I have not yet commit the fix, was waiting for confirmation it was working first. Kind Regards Bryce From: nygage ***@***.***> Reply to: brycelarge/xteve-vpn ***@***.***> Date: Sunday, 19 March 2023 at 21:07 To: brycelarge/xteve-vpn ***@***.***> Cc: ***@***.***" ***@***.***>, Comment ***@***.***> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) I'm not able to see It, the last commits i see are from 2 days ago. I've checked also to see if there is a dev branch, but i dont see It Yes there is a new build which I pushed just before replying to you. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 20:21 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. … -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [ "DEBUG=true", "PGID=1001", "OPENVPN_PROVIDER=CUSTOM", "LOCAL_NETWORK=192.168.0.0/24", "PRIVOXY_ENABLED=true", "NAME_SERVERS=1.1.1.1,1.0.0.1", "PUID=1001", "OPENVPN_USERNAME=", "OPENVPN_PASSWORD=", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "HOME=/root", "LANGUAGE=en_US.UTF-8", "LANG=en_US.UTF-8", "TERM=xterm", "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0", "S6_VERBOSITY=1", "S6_STAGE2_HOOK=/docker-mods", "XTEVE_BRANCH=master", "XTEVE_PORT=34400", "XTEVE_DEBUG=0", "TZ=Africa/Johannesburg", "OPENVPN_CONFIG=None", "CREATE_TUN_DEVICE=true", "OPENVPN_OPTIONS=", "OPENVPN_PROTOCOL=udp" ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Hello, Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by brycelarge** [comment]
Hi,Replace your vpn config file and pull the latest image from docker hub and let me know if it’s fixed?Sent from my iPhoneOn 19 Mar 2023, at 22:17, nygage ***@***.***> wrote:﻿
Oh, thanks for the clarification, i was manually building the image. I have tested with the new one image but it seems that it is not adding the information properly to the .ovpn file:
Original .ovpn file:

Crypto
cipher AES-128-CBC
auth SHA256
auth-user-pass

After the script:

Crypto
data-data-data-data-data-data-data-data-data-data-data-data-data-ciphersssssssssssss AES-128-CBC
auth SHA256
auth-user-pass /config/openvpn/custom-openvpn-credentials.txt

And the error which i'm receiving is the following one:

2023-03-19 22:11:01 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/configuration.ovpn:15: data-data-data-data-data-data-data-data-data-data-data-data-cipherssssssssssss (2.5.5)
Use --help for more information.

Thanks!

Are you looking at the git repo? I built and pushed up to docker hub so pulling the latest image has the fix. I have not yet commit the fix, was waiting for confirmation it was working first. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 21:07 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) I'm not able to see It, the last commits i see are from 2 days ago. I've checked also to see if there is a dev branch, but i dont see It Yes there is a new build which I pushed just before replying to you. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 20:21 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. … -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [ "DEBUG=true", "PGID=1001", "OPENVPN_PROVIDER=CUSTOM", "LOCAL_NETWORK=192.168.0.0/24", "PRIVOXY_ENABLED=true", "NAME_SERVERS=1.1.1.1,1.0.0.1", "PUID=1001", "OPENVPN_USERNAME=", "OPENVPN_PASSWORD=", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "HOME=/root", "LANGUAGE=en_US.UTF-8", "LANG=en_US.UTF-8", "TERM=xterm", "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0", "S6_VERBOSITY=1", "S6_STAGE2_HOOK=/docker-mods", "XTEVE_BRANCH=master", "XTEVE_PORT=34400", "XTEVE_DEBUG=0", "TZ=Africa/Johannesburg", "OPENVPN_CONFIG=None", "CREATE_TUN_DEVICE=true", "OPENVPN_OPTIONS=", "OPENVPN_PROTOCOL=udp" ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Hello, Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

**Comment by nygage** [comment]
Hi, 

Great! Now it is connecting to OpenVPN without issues.

Thanks a lot for your support! 


> Hi,Replace your vpn config file and pull the latest image from docker hub and let me know if it’s fixed?Sent from my iPhoneOn 19 Mar 2023, at 22:17, nygage ***@***.***> wrote:﻿ Oh, thanks for the clarification, i was manually building the image. I have tested with the new one image but it seems that it is not adding the information properly to the .ovpn file: Original .ovpn file: Crypto cipher AES-128-CBC auth SHA256 auth-user-pass After the script: Crypto data-data-data-data-data-data-data-data-data-data-data-data-data-ciphersssssssssssss AES-128-CBC auth SHA256 auth-user-pass /config/openvpn/custom-openvpn-credentials.txt And the error which i'm receiving is the following one: 2023-03-19 22:11:01 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/configuration.ovpn:15: data-data-data-data-data-data-data-data-data-data-data-data-cipherssssssssssss (2.5.5) Use --help for more information. Thanks! Are you looking at the git repo? I built and pushed up to docker hub so pulling the latest image has the fix. I have not yet commit the fix, was waiting for confirmation it was working first. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 21:07 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) I'm not able to see It, the last commits i see are from 2 days ago. I've checked also to see if there is a dev branch, but i dont see It Yes there is a new build which I pushed just before replying to you. Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 20:21 To: brycelarge/xteve-vpn @.> Cc: @." @.>, Comment @.> Subject: Re: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello, I think I found the issue, just ushed the new build up so pull and let me know if that sorts it out? Kind Regards Bryce From: nygage @.> Reply to: brycelarge/xteve-vpn @.> Date: Sunday, 19 March 2023 at 17:42 To: brycelarge/xteve-vpn @.> Cc: Subscribed @.> Subject: [brycelarge/xteve-vpn] File not found: custom-openvpn-credentials.txt': No such file or directory (errno=2) (Issue #15) Hello Bryce, Firstly let me thank you for sharing this container, i think everyone should be using it with xteve. I have completed all the steps to use a custom provider but when I run the container I receive these errors which seems to indicate that there are some missing files. … -----END CERTIFICATE----- 2023-03-19 17:32:30 [OpenVPN] Adding to /etc/resolv.conf 2023-03-19 17:32:30 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set. 2023-03-19 17:32:30 WARNING: cannot stat file '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: --auth-user-pass fails with '/config/openvpn/custom-openvpn-credentials.txt': No such file or directory (errno=2) Options error: Please correct these errors. I have performed an ispect to the container to check what could be happening but the vars seems to be correctly set and received by the container "Env": [ "DEBUG=true", "PGID=1001", "OPENVPN_PROVIDER=CUSTOM", "LOCAL_NETWORK=192.168.0.0/24", "PRIVOXY_ENABLED=true", "NAME_SERVERS=1.1.1.1,1.0.0.1", "PUID=1001", "OPENVPN_USERNAME=", "OPENVPN_PASSWORD=", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "HOME=/root", "LANGUAGE=en_US.UTF-8", "LANG=en_US.UTF-8", "TERM=xterm", "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0", "S6_VERBOSITY=1", "S6_STAGE2_HOOK=/docker-mods", "XTEVE_BRANCH=master", "XTEVE_PORT=34400", "XTEVE_DEBUG=0", "TZ=Africa/Johannesburg", "OPENVPN_CONFIG=None", "CREATE_TUN_DEVICE=true", "OPENVPN_OPTIONS=", "OPENVPN_PROTOCOL=udp" ], Could you please help me to figure out what can be happening? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Hello, Thanks for your quick response Bryce, I'm already using the last build from 2 days ago is there any one newer? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
